"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from dataclasses_json import Undefined, dataclass_json
from sunflower_labs_rest_api import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AuthTokenRequestBody:
    api_key: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('apiKey') }})
    hive_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('hiveId') }})
    



@dataclasses.dataclass
class AuthTokenRequest:
    request_body: Optional[AuthTokenRequestBody] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    valid_for_seconds: Optional[float] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'valid_for_seconds', 'style': 'form', 'explode': True }})
    r"""Lifetime of the requested token in seconds"""
    



@dataclasses.dataclass
class AuthTokenResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    

